---
#uncomment and change default settings as needed

okd_cluster_name: okdpoc
okd_base_domain: saft.in

# If you don't set a specific okd_version, tha lates from the stable strem will be used.
# If it does not work well, try to step back using specific releases from:
# https://github.com/openshift/okd/releases/
#
# okd_version: 

# You can skip specifyng okd_fcos_image, it  will be filled in later by running image-installer.yml playbook
# Don't uncomment it though. 

okd_fcos_image:


# okd_loadbalancer_flavor: "lm.small"
# okd_master_flavor: "lm.large.1d"
# okd_worker_flavor: "lm.medium.1d"

# okd_masters: 3
# okd_workers: 2

api_cidrs:
  - 0.0.0.0/0
ssh_cidrs:
  - 0.0.0.0/0

# The size of ignition for boot node is too big to send directly to the Nova API
# so it needs to be uploaded to bucket and pulle from ther instead.
# You must export AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
# and the bucket name must exist
s3_bucket: "your-bucket-name"
s3_filename: "{{okd_cluster_name}}-{{okd_base_domain}}.ign"

# Change endpoint url if you s3 bucket resides elsewhere
# Make sure that aws s3 presign works on the bucket objekt.
s3_endpoint_url: "https://minio-1.safedc.net:9091"

ssh_key_path: "~/.ssh/id_rsa.pub"
